# Pandas

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

### 1

In [2]:
arr1 = np.arange(9).reshape(3, 3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
arr2 = np.arange(9).reshape(3, 3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1, arr2])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1, arr2], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

### 2

In [8]:
arr3 = np.arange(9).reshape(3, 3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr4 = np.arange(12).reshape(3, 4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
np.concatenate([arr3, arr4])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [11]:
np.concatenate([arr3, arr4], axis=1)

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11]])

### 3

In [13]:
s1 = Series([1, 2, 3], index=['X', 'Y', 'Z'])
s1

X    1
Y    2
Z    3
dtype: int64

In [14]:
s2 = Series([4, 5], index=['A', 'B'])
s2

A    4
B    5
dtype: int64

In [15]:
pd.concat([s1, s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [17]:
pd.concat([s1, s2], axis=1)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
A  NaN  4.0
B  NaN  5.0
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN

### 4

In [18]:
df1 = DataFrame(np.random.randn(3, 3), columns=['X', 'Y', 'Z'])
df1

X         Y         Z
0 -0.154423 -0.180620 -2.399345
1 -0.728132 -1.185044  0.179576
2 -1.072465  0.424407  1.351534

In [20]:
df2 = DataFrame(np.random.randn(3, 3), columns=['X', 'Y', 'A'])
df2

X         Y         A
0  0.118365 -0.998334 -0.740557
1 -0.563035 -0.402438  0.021494
2  1.432642 -0.919571 -1.901871

In [21]:
pd.concat([df1, df2])

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A         X         Y         Z
0       NaN -0.154423 -0.180620 -2.399345
1       NaN -0.728132 -1.185044  0.179576
2       NaN -1.072465  0.424407  1.351534
0 -0.740557  0.118365 -0.998334       NaN
1  0.021494 -0.563035 -0.402438       NaN
2 -1.901871  1.432642 -0.919571       NaN

In [22]:
pd.concat([df1, df2], axis=1)

X         Y         Z         X         Y         A
0 -0.154423 -0.180620 -2.399345  0.118365 -0.998334 -0.740557
1 -0.728132 -1.185044  0.179576 -0.563035 -0.402438  0.021494
2 -1.072465  0.424407  1.351534  1.432642 -0.919571 -1.901871

### 5

In [23]:
s3 = Series([1, np.nan, 3, np.nan], index=['A', 'B', 'C', 'D'])
s3

A    1.0
B    NaN
C    3.0
D    NaN
dtype: float64

In [24]:
s4 = Series([1, 2, 3, 4], index=['A', 'B', 'C', 'D'])
s4

A    1
B    2
C    3
D    4
dtype: int64

In [25]:
s3.combine_first(s4)

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float64

### 6

In [27]:
df3 = DataFrame({'X': [1, np.nan, 3, np.nan], 
                 'Y': [5, np.nan, 7, np.nan], 
                 'Z': [9, np.nan, 11, np.nan]})
df3

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [28]:
df4 = DataFrame({'Z': [np.nan, 10, np.nan, 12], 
                 'A': ['a', 'b', 'c', 'd']})
df4

Z  A
0   NaN  a
1  10.0  b
2   NaN  c
3  12.0  d

In [29]:
df3.combine_first(df4)

A    X    Y     Z
0  a  1.0  5.0   9.0
1  b  NaN  NaN  10.0
2  c  3.0  7.0  11.0
3  d  NaN  NaN  12.0